"use client";

import { useState } from "react";

type Props = {
  product: string;
  reason: string;
  policyResult: string;
  riskSignals: string[];
  evidenceAssessment: string;
  recommendation: string;
};

export function AiCaseSummary(props: Props) {
  const [summary, setSummary] = useState<string | null>(null);
  const [source, setSource] = useState<"claude" | "template" | null>(null);
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true);
    try {
      const response = await fetch("/api/ai/case-summary", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(props) });
      const result = await response.json() as { summary?: string; source?: "claude" | "template" };
      if (response.ok && result.summary) { setSummary(result.summary); setSource(result.source ?? "template"); }
      else setSummary("A summary could not be generated right now. The verified investigation details are shown below.");
    } catch { setSummary("A summary could not be generated right now. The verified investigation details are shown below."); }
    finally { setLoading(false); }
  }

  return (
    <section className="case-section ai-summary">
      <div className="section-title-row">
        <div>
          <div className="ai-header-badge-row">
            <span className="ai-summary-badge">✦ CLAUDE AI ANALYSIS</span>
          </div>
          <h2>AI case summary</h2>
          <p>Synthesized from verified policy checks and customer evidence.</p>
        </div>
        <button
          type="button"
          className="text-button ai-action-btn"
          onClick={generate}
          disabled={loading}
        >
          {loading ? "Generating summary…" : summary ? "Refresh analysis ↻" : "Generate analysis →"}
        </button>
      </div>

      {summary ? (
        <div className="ai-summary-result">
          <p className="summary-copy">{summary}</p>
          <div className="ai-source-badge">
            <span className="source-dot" />
            <small>{source === "claude" ? "Generated by Claude 3.5 Sonnet" : "Verified-facts policy synthesis"}</small>
          </div>
        </div>
      ) : (
        <p className="summary-placeholder">
          Generate a concise, automated policy and evidence explanation before making your final return decision.
        </p>
      )}
    </section>
  );
}
